CREATE UNIQUE INDEX IF NOT EXISTS UX_153cda_Id ON fizz.Assignment(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_f12526_Id ON fizz.AssignmentSubmission(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_0b99df_Id ON fizz.LMSGrade(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_2df970_Id ON fizz.LMSSection(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_b512d9_Id ON fizz.User(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_517447_Id ON fizz.UserAttendanceEvent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_5c3d9d_Id ON fizz.UserLMSActivity(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_f5b624_Id ON fizz.UserLMSSectionAssociation(Id);

